resources:
  - name: runpopprop
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: runpopprop2
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: runpopprop3
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
pipelines: 
  - name: TRIGGER
    steps:
      - name: TRIGGER
        type: Bash
        configuration:
          outputResources:
            - name: runpopprop
        execution:
          onExecute:
            - write_output runpopprop runId=$run_number
  - name: TRIGGER_OUT_1_1
    steps:
      - name: TRIGGER_OUT_1
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          outputResources:
            - name: runpopprop3
        execution:
          onExecute:
            - printenv
            - write_output runpopprop3 runId=$run_number            
  - name: TRIGGER_OUT_3_3
    steps:
      - name: TRIGGER_OUT_1
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop3
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_1_2
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          outputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_1_3
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_1_4
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          outputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_3_1
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_3_2
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv




