resources:
  - name: runpopprop
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: runpopprop2
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
  - name: runpopprop3
    type: PropertyBag
    configuration:
      key1: value1
      key2: value2
pipelines: 
  - name: TRIGGER
    steps:
      - name: TRIGGER
        type: Bash
        configuration:
          outputResources:
            - name: runpopprop
        execution:
          onStart:
            #- msg="Run description updated from step $step_id"
            - update_run_description "test"
            - set_run_name "1.1.1"
          onExecute:
            - write_output runpopprop runId=$run_number
  - name: TRIGGER_OUT_1_1
    steps:
      - name: TRIGGER_OUT_1
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          outputResources:
            - name: runpopprop3
        execution:
          onStart:
            #- msg="Run description updated from step $step_id"
            - update_run_description "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
            - set_run_name "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."        
          onExecute:
            - printenv
            #- write_output runpopprop3 runId=$run_number            
  - name: TRIGGER_OUT_3_3
    steps:
      - name: TRIGGER_OUT_1
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop3
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_1_2
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          outputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_1_3
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_1_4
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop
          outputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_3_1
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv
  - name: TRIGGER_OUT_3_2
    steps:
      - name: TRIGGER_OUT_2
        type: Bash
        configuration:
          inputResources:
            - name: runpopprop2
          environmentVariables:
            SOME_KEY: 'asd'
        execution:
          onExecute:
            - printenv




